# docker-compose.yml
services:
  db:
    image: mysql:8.0
    container_name: camara_db
    restart: always
    environment:
      MYSQL_DATABASE: camara_chamados
      MYSQL_ROOT_PASSWORD: senhachamadosmariana
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: camara_backend
    restart: always
    ports:
      - "8000:8000"
    # O extra_hosts cria um atalho de rede seguro para o contêiner enxergar a sua máquina nativa
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=mysql+pymysql://root:senhachamadosmariana@host.docker.internal:3307/camara_chamados

  frontend:
    image: nginx:alpine
    container_name: camara_frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  mysql_data: