# docker-compose.yml
services:
  db:
    image: mysql:8.0
    container_name: camara_db
    restart: always
    environment:
      MYSQL_DATABASE: camara_chamados
      MYSQL_ROOT_PASSWORD: senhachamadosmariana
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: camara_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:senhachamadosmariana@db:3306/camara_chamados
      - SECRET_KEY=fala-ai-local-dev-secret
      - ACCESS_TOKEN_EXPIRE_MINUTES=120
    volumes:
      - ./tests:/app/tests
      - ./backend/uploads:/app/backend/uploads
    depends_on:
      - db

volumes:
  mysql_data:
